default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 500

development:
  <<: *default
  database: api_dev
  host: localhost
  pool: 5
  username: postgres
  password: 12345678

test:
  <<: *default
  database: api_test
  host: localhost
  pool: 5
  username: postgres
  password: 12345678
